G3 display recipe
Mayden-Academy/2019-geckos-grub pull request #14
Opened 2019-11-05 14:54 UTC by jdselby24

2019-11-05 16:00 UTC, ashleycoles requested changes

2019-11-05 16:00 UTC, ashleycoles commented on index.php
> +$db = new GRUB\Db();
No need to instantiate an object if you are only using a static method

2019-11-05 16:00 UTC, ashleycoles commented on src/Curl.php
> +    public function __construct($ingredients)
Constructors should generally be the first method in a class, just because they run first.

2019-11-05 16:00 UTC, ashleycoles commented on src/Curl.php
> +    public function __construct($ingredients)
It seems a bit strange that you take the ingredients (not type hinted) in the constructor, it might make more sense to have the constructor create the curl handler instead, and then the makeRequest method takes the ingredients and actually sends the request.

2019-11-05 16:00 UTC, ashleycoles commented on src/Curl.php
> +        $ch = curl_init();
$ch gets created for every single request, if you ever needed to make multiple requests then it would be a bit of a waste. Better to create $ch in the constructor instead.

2019-11-05 16:00 UTC, ashleycoles commented on src/Curl.php
> +class Curl {
Missing docblock

2019-11-05 16:00 UTC, ashleycoles commented on src/IngredientHydrator.php
> +        $query->execute();
Why is the query running in the constructor?

2019-11-05 16:00 UTC, ashleycoles commented on src/IngredientHydrator.php
> +        return $this->ingredients;
You should really run and return the query here instead, the constructor should just get the class ready to work (so setting property that contains your DB object)

2019-11-05 16:00 UTC, ashleycoles commented on src/IngredientHydrator.php
> +     * @param array $results
This method does not take a param

2019-11-05 16:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +            }
Try and avoid setting/resetting properties like the imageURL. Check before setting, then you can just set the property a single time.

2019-11-05 16:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +     * @param array $ingredients Array of the ingredients required for the recipe
This no longer seems to be an array

2019-11-05 16:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +
Remove whitespace
```suggestion
```

2019-11-05 16:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +            $this->ingredients = $this->limit_ingredients($ingredients);
Try and avoid setting this twice

2019-11-05 16:00 UTC, ashleycoles commented on src/RecipeHydrator.php
> +class RecipeHydrator
Missing docblock

2019-11-05 16:00 UTC, ashleycoles commented on src/recipeHydrator.php
> +<?php
This shouldn't be here

2019-11-05 16:00 UTC, ashleycoles commented on recipes.php
> +}
I think this should be in some kind of validator object

2019-11-05 16:07 UTC, jdselby24 commented on index.php
> +$db = new GRUB\Db();
```suggestion
```

2019-11-05 16:07 UTC, jdselby24 commented on src/Curl.php
> +class Curl {
```suggestion
/**
* Used for creating an API connection
**/
class Curl {
```

2019-11-05 16:07 UTC, jdselby24 commented on src/IngredientHydrator.php
> +     * @param array $results
```suggestion
```

2019-11-05 16:07 UTC, jdselby24 commented on src/IngredientHydrator.php
> +        return $this->ingredients;
```suggestion
$query = $db->prepare("SELECT `name` FROM `ingredients`;");
        $query->setFetchMode(\PDO::FETCH_CLASS, 'GRUB\IngredientEntity');
        $query->execute();
        return $query->fetchAll();
```

2019-11-05 16:07 UTC, jdselby24 commented on src/RecipeEntity.php
> +     * @param array $ingredients Array of the ingredients required for the recipe
```suggestion
     * @param string $ingredients Array of the ingredients required for the recipe
```

2019-11-05 16:07 UTC, jdselby24 commented on src/RecipeEntity.php
> +              $this->imageURL = $imageURL;
```suggestion
```

2019-11-05 16:07 UTC, jdselby24 commented on src/RecipeEntity.php
> +            }
suggestion made

2019-11-05 16:07 UTC, jdselby24 commented on src/RecipeEntity.php
> +              $this->ingredients = html_entity_decode($ingredients);
```suggestion
```
uneeded

2019-11-05 16:09 UTC, jdselby24 commented on src/Curl.php
> +        $ch = curl_init();
```suggestion
```

2019-11-05 16:09 UTC, jdselby24 commented on src/Curl.php
> +    $this->ingredients = $ingredients;
```suggestion
    $this->ch = curl_init();
    $this->ingredients = $ingredients;
```

2019-11-05 16:09 UTC, jdselby24 commented on src/Curl.php
> +        curl_close($ch);
```suggestion
        curl_close($this->ch);
```

2019-11-05 16:09 UTC, jdselby24 commented on src/Curl.php
> +        $output = curl_exec($ch);
```suggestion
        $output = curl_exec($this->ch);
```

2019-11-05 16:09 UTC, jdselby24 commented on src/Curl.php
> +        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
```suggestion
        curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, 1);
```

2019-11-05 16:10 UTC, jdselby24 commented on src/Curl.php
> +        curl_setopt($ch, CURLOPT_URL, self::BASEURL . '?i=' . $ingredientsString);
```suggestion
        curl_setopt($this->ch, CURLOPT_URL, self::BASEURL . '?i=' . $ingredientsString);
```

2019-11-05 16:10 UTC, jdselby24 commented on src/Curl.php
> +
```suggestion
private $ch;
```

2019-11-05 16:15 UTC, jdselby24 commented on src/RecipeEntity.php
> +            }
```suggestion
            } else {
                $this->imgURL = $imageURL;
            }
```

2019-11-06 08:31 UTC, jdselby24 commented on src/Curl.php
> +    public function __construct($ingredients)
```suggestion
    public function __construct(array $ingredients)
```

2019-11-06 09:00 UTC, ashleycoles requested changes

2019-11-06 09:00 UTC, ashleycoles commented on src/Validator.php
> +public static function validateForm(array $formData) :array {
Fix indenting

2019-11-06 09:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +class RecipeEntity {
Missing class docblock

2019-11-06 09:00 UTC, ashleycoles commented on src/RecipeEntity.php
> +    private $ingredients = "";
Missing property docblocks

2019-11-06 09:00 UTC, ashleycoles commented on src/IngredientHydrator.php
> +    private $db;
Missing docblock

2019-11-06 09:00 UTC, ashleycoles commented on src/Curl.php
> +    const BASEURL = "http://www.recipepuppy.com/api/";
Missing docblock

2019-11-06 09:00 UTC, ashleycoles commented on tests/recipes.php
> +<?php
Seems like these tests are failing

2019-11-06 09:53 UTC, ashleycoles approved these changes

2019-11-06 09:53 UTC, merged